[package]
name = "sleigh"
version = "0.1.0"
edition = "2024"
default-run = "sleigh"

[dependencies]
aoc-client = "0.2"
chrono = "0.4.38"

clap = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
